server.port=55622

spring.application.name = procgenjs
spring.devtools.add-properties = false

#spring.datasource.url=org.hsqldb.jdbc.JDBCDriver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database: HSQL
#
#spring.jpa.hibernate.show_sql=true
#spring.jpa.hibernate.hbm2ddl.auto=update
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
#
#endpoints.shutdown.sensitive=false
#endpoints.shutdown.enabled=true
#management.endpoint.shutdown.enabled=true
#management.endpoints.web.expose=*
#management.endpoints.web.exposure.include=*
##
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher
#spring.datasource.url=jdbc:hsqldb:file:hsqldb;hsqldb.cache_rows=10shutdown=true;hsqldb.write_delay=false;
##spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
#spring.datasource.username = sa
#hibernate.dialect=org.hibernate.dialect.HSQLDialect

#spring.jpa.database-platform=com.colorpro.config.SQLDialect
spring.jpa.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.ddl-auto=update
#
#
spring.datasource.url = jdbc:sqlite:./dataFolder/database/procgenjs.db
spring.datasource.driver-class-name = org.sqlite.JDBC

#spring.datasource.username = admin
#spring.datasource.password = admin

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#spring.web.resources.static-locations=file:///D:/w/d/server/procgen/procgen/files,classpath:/files/,classpath:/public/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#springdoc.packagesToScan=com.colorpro.controller
#springdoc.pathsToMatch=/v1, /api/balance/**
